<?php
  //create module
  function cipher_menu(){
    //make module a menu link
    $items['cipher'] = array(
      'title' => 'Shift Cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    //make result page
    $items['result'] = array(
      'title' => 'Shift Cipher Result',
      'page callback' => 'cipher_success',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  //provide form arguments
  function cipher_form()
  {
    //form field with validations
    $form['string'] = array(
      '#title'=> 'Input string',
      '#description' => 'Enter the word you want to cipher',
      '#type' => 'textfield',
      '#element_validate' => array('element_validate_string'),
      '#required' => TRUE,
    );
    $form['number'] = array(
      '#title'=> 'Input number',
      '#description' => 'Enter the shift cipher number',
      '#type' => 'textfield',
      '#element_validate' => array('element_validate_number','element_validate_integer_positive', 'element_validate_range'),
      '#required' => TRUE,  );
    $form['direction'] = array(
      '#title'=> 'Input direction',
      '#description' => 'Enter the shift cipher direction',
      '#type' => 'textfield',
      '#element_validate' => array('element_validate_direction'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Caesar Cipher',
    );
    return $form;
  }

  function element_validate_range($element){
    if ($element['#value'] > 26 ) {
        form_error($element, t('Number must be less than or equal to 26.'));
    }
  }
  //Use regex to validate
  function element_validate_string($element){
    if (preg_match('/[^a-zA-Z.,!?;\s]/',$element['#value']) != 0){
      form_error($element,t("Please don't enter numbers or special characters except for punctuations"));
    }
  }

  //use if statements to validate
  function element_validate_direction($element){
    if (!($element['#value'] === "left" || $element['#value'] === "right")){
      form_error($element,t("Please only enter 'left' or 'right' (lowercase)"));
    }
  }

  function cipher_form_submit($form, &$form_state){
    $string = $form_state['values']['string'];
    $number = $form_state['values']['number'];
    $direction = $form_state['values']['direction'];
    $split = explode(" ",$string);
    $output = array();
    foreach ($split as $word) {
        $new_word = cipher_each($word, $direction, $number);
        array_push($output, $new_word);
    }
    $_SESSION['result'] = implode(" ",$output);
    $form_state['redirect'] = 'result';
  }

  function cipher_each($word, $direction, $number){
    $chars = str_split($word);
    $output = array();
    foreach ($chars as $letter) {
      if (preg_match('/[.,!?;]/', $letter) === 0) {
        if($direction === 'right'){
          $new_charval = ord($letter) + intval($number);
        } else {
          $new_charval = ord($letter) - intval($number);
        }

        //make sure within bounds
        if($new_charval > 122){
          $new_charval = $new_charval - 25;
        } elseif ($new_charval < 97) {
          $new_charval = $new_charval + 25;
        }

        $new_letter = chr($new_charval);
        array_push($output, $new_letter);
      } else {
        array_push($output, $letter);
      }
    }
    $result = join($output);
    return $result;
  }

  function cipher_success(){
    return '<p> Your ciphered string is ' . $_SESSION['result'] . ' <p>';
  }
